-- Fresh-install bootstrap schema for Hada.
-- Generated from supabase/migrations for brand-new databases.
-- Do not edit this file directly.
-- Regenerate with: npm run db:schema
-- Existing databases should continue applying incremental migrations.

-- ====================================================================
-- BEGIN 001_initial_schema.sql
-- ====================================================================
-- Hada Database Schema
-- Run this in your Supabase SQL Editor

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Users table (extends Supabase auth.users)
create table public.users (
  id uuid references auth.users on delete cascade primary key,
  email text not null,
  name text,
  avatar_url text,
  tier text not null default 'free' check (tier in ('free', 'paid', 'pro')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Conversations table
create table public.conversations (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.users on delete cascade not null,
  title text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Messages table
create table public.messages (
  id uuid default uuid_generate_v4() primary key,
  conversation_id uuid references public.conversations on delete cascade not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  metadata jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Integrations table (for Google, Microsoft OAuth tokens)
create table public.integrations (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.users on delete cascade not null,
  provider text not null check (provider in ('google', 'microsoft')),
  access_token text not null,
  refresh_token text not null,
  expires_at timestamp with time zone not null,
  scopes text[] not null default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, provider)
);

-- Enable Row Level Security
alter table public.users enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.integrations enable row level security;

-- Users policies
create policy "Users can view own profile" on public.users
  for select using (auth.uid() = id);

create policy "Users can update own profile" on public.users
  for update using (auth.uid() = id);

-- Conversations policies
create policy "Users can view own conversations" on public.conversations
  for select using (auth.uid() = user_id);

create policy "Users can create conversations" on public.conversations
  for insert with check (auth.uid() = user_id);

create policy "Users can update own conversations" on public.conversations
  for update using (auth.uid() = user_id);

create policy "Users can delete own conversations" on public.conversations
  for delete using (auth.uid() = user_id);

-- Messages policies
create policy "Users can view messages in own conversations" on public.messages
  for select using (
    exists (
      select 1 from public.conversations
      where conversations.id = messages.conversation_id
      and conversations.user_id = auth.uid()
    )
  );

create policy "Users can create messages in own conversations" on public.messages
  for insert with check (
    exists (
      select 1 from public.conversations
      where conversations.id = messages.conversation_id
      and conversations.user_id = auth.uid()
    )
  );

-- Integrations policies
create policy "Users can view own integrations" on public.integrations
  for select using (auth.uid() = user_id);

create policy "Users can create own integrations" on public.integrations
  for insert with check (auth.uid() = user_id);

create policy "Users can update own integrations" on public.integrations
  for update using (auth.uid() = user_id);

create policy "Users can delete own integrations" on public.integrations
  for delete using (auth.uid() = user_id);

-- Function to automatically create user profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, name, avatar_url)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'name',
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to create user profile on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Function to update updated_at timestamp
create or replace function public.update_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

-- Triggers for updated_at
create trigger update_users_updated_at
  before update on public.users
  for each row execute procedure public.update_updated_at();

create trigger update_conversations_updated_at
  before update on public.conversations
  for each row execute procedure public.update_updated_at();

create trigger update_integrations_updated_at
  before update on public.integrations
  for each row execute procedure public.update_updated_at();

-- Indexes for performance
create index idx_conversations_user_id on public.conversations(user_id);
create index idx_messages_conversation_id on public.messages(conversation_id);
create index idx_messages_created_at on public.messages(created_at);
create index idx_integrations_user_id on public.integrations(user_id);

-- END 001_initial_schema.sql

-- ====================================================================
-- BEGIN 002_add_user_permissions.sql
-- ====================================================================
-- Add permissions column to users table for configurable action permissions
-- This allows users to control whether actions require confirmation or execute directly

alter table public.users
  add column permissions jsonb default '{
    "google_calendar_read": "direct",
    "google_calendar_write": "confirm",
    "google_gmail_read": "direct",
    "google_gmail_send": "confirm"
  }'::jsonb;

-- Add comment explaining the structure
comment on column public.users.permissions is 'User action permissions. Keys are permission names, values are "direct" (execute immediately) or "confirm" (require user confirmation).';

-- END 002_add_user_permissions.sql

-- ====================================================================
-- BEGIN 004_agent_and_telegram.sql
-- ====================================================================
-- Agent loop + Telegram integration schema

create extension if not exists pgcrypto;

-- Allow system compaction messages
alter table public.messages
  drop constraint if exists messages_role_check;

alter table public.messages
  add constraint messages_role_check
  check (role in ('user', 'assistant', 'system'));

-- Conversation compaction marker
alter table public.conversations
  add column if not exists compacted_through timestamp with time zone;

-- User settings for provider/model preferences and future options
alter table public.users
  add column if not exists settings jsonb not null default jsonb_build_object(
    'llm_provider', 'minimax',
    'llm_model', null
  );

comment on column public.users.settings is 'User settings JSON (provider/model/timezone and future preferences).';

-- Extend integrations to support telegram and token-less providers
alter table public.integrations
  drop constraint if exists integrations_provider_check;

alter table public.integrations
  add constraint integrations_provider_check
  check (provider in ('google', 'microsoft', 'telegram'));

alter table public.integrations
  alter column refresh_token drop not null;

alter table public.integrations
  alter column expires_at drop not null;

-- Topic-keyed long-term memory
create table if not exists public.user_memories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  topic text not null,
  content text not null,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),
  unique(user_id, topic)
);

-- Temporary token for Telegram account linking
create table if not exists public.telegram_link_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  token text not null unique,
  expires_at timestamp with time zone not null,
  used_at timestamp with time zone,
  created_at timestamp with time zone not null default timezone('utc'::text, now())
);

-- Scheduled one-time and recurring tasks
create table if not exists public.scheduled_tasks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  type text not null check (type in ('once', 'recurring')),
  cron_expression text,
  run_at timestamp with time zone,
  description text not null,
  enabled boolean not null default true,
  last_run_at timestamp with time zone,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  check (
    (type = 'once' and run_at is not null and cron_expression is null) or
    (type = 'recurring' and cron_expression is not null)
  )
);

-- RLS
alter table public.user_memories enable row level security;
alter table public.telegram_link_tokens enable row level security;
alter table public.scheduled_tasks enable row level security;

-- user_memories policies
create policy "Users can view own memories" on public.user_memories
  for select using (auth.uid() = user_id);

create policy "Users can create own memories" on public.user_memories
  for insert with check (auth.uid() = user_id);

create policy "Users can update own memories" on public.user_memories
  for update using (auth.uid() = user_id);

create policy "Users can delete own memories" on public.user_memories
  for delete using (auth.uid() = user_id);

-- telegram_link_tokens policies
create policy "Users can view own telegram tokens" on public.telegram_link_tokens
  for select using (auth.uid() = user_id);

create policy "Users can create own telegram tokens" on public.telegram_link_tokens
  for insert with check (auth.uid() = user_id);

create policy "Users can delete own telegram tokens" on public.telegram_link_tokens
  for delete using (auth.uid() = user_id);

-- scheduled_tasks policies
create policy "Users can view own scheduled tasks" on public.scheduled_tasks
  for select using (auth.uid() = user_id);

create policy "Users can create own scheduled tasks" on public.scheduled_tasks
  for insert with check (auth.uid() = user_id);

create policy "Users can update own scheduled tasks" on public.scheduled_tasks
  for update using (auth.uid() = user_id);

create policy "Users can delete own scheduled tasks" on public.scheduled_tasks
  for delete using (auth.uid() = user_id);

-- updated_at trigger for user_memories
drop trigger if exists update_user_memories_updated_at on public.user_memories;
create trigger update_user_memories_updated_at
  before update on public.user_memories
  for each row execute procedure public.update_updated_at();

-- Indexes
create index if not exists idx_user_memories_user_updated
  on public.user_memories(user_id, updated_at desc);

create index if not exists idx_telegram_link_tokens_token
  on public.telegram_link_tokens(token);

create index if not exists idx_telegram_link_tokens_expires_at
  on public.telegram_link_tokens(expires_at);

create index if not exists idx_scheduled_tasks_due_once
  on public.scheduled_tasks(enabled, run_at)
  where type = 'once';

create index if not exists idx_scheduled_tasks_due_recurring
  on public.scheduled_tasks(enabled, cron_expression, last_run_at)
  where type = 'recurring';

-- END 004_agent_and_telegram.sql

-- ====================================================================
-- BEGIN 005_agent_runs.sql
-- ====================================================================
create table if not exists public.agent_runs (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  conversation_id uuid references public.conversations(id) on delete set null,
  source text not null default 'web' check (source in ('web', 'telegram', 'scheduled')),
  status text not null default 'running' check (status in ('running', 'completed', 'failed', 'timeout')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_ms integer,
  input_preview text,
  output_preview text,
  tool_calls jsonb not null default '[]'::jsonb,
  error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_agent_runs_user
  on public.agent_runs(user_id, started_at desc);

create index if not exists idx_agent_runs_status
  on public.agent_runs(user_id, status)
  where status = 'running';

alter table public.agent_runs enable row level security;

create policy "Users can view own agent runs"
  on public.agent_runs
  for select
  using (auth.uid() = user_id);

create policy "Users can insert own agent runs"
  on public.agent_runs
  for insert
  with check (auth.uid() = user_id);

create policy "Users can update own agent runs"
  on public.agent_runs
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- END 005_agent_runs.sql

-- ====================================================================
-- BEGIN 006_background_jobs.sql
-- ====================================================================
create table if not exists public.background_jobs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_message_id uuid not null references public.messages(id) on delete cascade,
  assistant_message_id uuid not null references public.messages(id) on delete cascade,
  source text not null check (source in ('web', 'telegram', 'scheduled')),
  request_text text not null,
  status text not null default 'queued' check (status in ('queued', 'running', 'completed', 'failed', 'timeout')),
  processing_token text,
  attempts integer not null default 0,
  started_at timestamptz,
  finished_at timestamptz,
  last_error text,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.background_job_events (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.background_jobs(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  seq integer not null,
  event jsonb not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  unique(job_id, seq)
);

alter table public.background_jobs enable row level security;
alter table public.background_job_events enable row level security;

create policy "Users can view own background jobs" on public.background_jobs
  for select using (auth.uid() = user_id);

create policy "Users can create own background jobs" on public.background_jobs
  for insert with check (auth.uid() = user_id);

create policy "Users can view own background job events" on public.background_job_events
  for select using (auth.uid() = user_id);

drop trigger if exists update_background_jobs_updated_at on public.background_jobs;
create trigger update_background_jobs_updated_at
  before update on public.background_jobs
  for each row execute procedure public.update_updated_at();

create index if not exists idx_background_jobs_user_created
  on public.background_jobs(user_id, created_at desc);

create index if not exists idx_background_jobs_queue
  on public.background_jobs(status, created_at asc)
  where status in ('queued', 'running');

create index if not exists idx_background_job_events_job_seq
  on public.background_job_events(job_id, seq asc);

-- END 006_background_jobs.sql

-- ====================================================================
-- BEGIN 007_memory_embeddings.sql
-- ====================================================================
-- Semantic memory support for long-term recall

create extension if not exists vector;

alter table public.user_memories
  add column if not exists embedding vector(1536);

create index if not exists idx_user_memories_embedding
  on public.user_memories
  using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

create or replace function public.match_user_memories(
  query_embedding vector(1536),
  match_user_id uuid,
  match_threshold float default 0.3,
  match_count int default 20
)
returns table (
  id uuid,
  topic text,
  content text,
  updated_at timestamptz,
  similarity float
)
language sql
stable
as $$
  select
    um.id,
    um.topic,
    um.content,
    um.updated_at,
    1 - (um.embedding <=> query_embedding) as similarity
  from public.user_memories um
  where um.user_id = match_user_id
    and um.embedding is not null
    and 1 - (um.embedding <=> query_embedding) > match_threshold
  order by um.embedding <=> query_embedding
  limit match_count;
$$;

-- END 007_memory_embeddings.sql

-- ====================================================================
-- BEGIN 008_messages_update_policy.sql
-- ====================================================================
-- Add UPDATE RLS policy for messages table
-- Required for feedback (thumbs up/down) and other message metadata updates

create policy "Users can update messages in own conversations" on public.messages
  for update using (
    exists (
      select 1 from public.conversations
      where conversations.id = messages.conversation_id
      and conversations.user_id = auth.uid()
    )
  );

-- END 008_messages_update_policy.sql

-- ====================================================================
-- BEGIN 009_default_openrouter_provider.sql
-- ====================================================================
-- Set OpenRouter as the default provider in user settings.
alter table public.users
  alter column settings set default jsonb_build_object(
    'llm_provider', 'openrouter',
    'llm_model', null
  );

-- END 009_default_openrouter_provider.sql

-- ====================================================================
-- BEGIN 010_documents.sql
-- ====================================================================
-- Documents table for user-managed RAG context
create table if not exists documents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  title text not null,
  content text not null default '',
  folder text,                          -- null = root; max one level e.g. 'Work'
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Index for fast user lookups
create index if not exists documents_user_id_idx on documents(user_id);
create index if not exists documents_user_folder_idx on documents(user_id, folder);

-- Auto-update updated_at
create or replace function update_documents_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger documents_updated_at
  before update on documents
  for each row execute procedure update_documents_updated_at();

-- RLS
alter table documents enable row level security;

create policy "Users can read own documents"
  on documents for select
  using (auth.uid() = user_id);

create policy "Users can insert own documents"
  on documents for insert
  with check (auth.uid() = user_id);

create policy "Users can update own documents"
  on documents for update
  using (auth.uid() = user_id);

create policy "Users can delete own documents"
  on documents for delete
  using (auth.uid() = user_id);

-- END 010_documents.sql

-- ====================================================================
-- BEGIN 011_agent_runs_delete_policy.sql
-- ====================================================================
-- Allow users to delete their own run history rows.
-- Required so chat-history clear actions can remove activity without service-role fallback.
create policy "Users can delete own agent runs"
  on public.agent_runs
  for delete
  using (auth.uid() = user_id);

-- END 011_agent_runs_delete_policy.sql

-- ====================================================================
-- BEGIN 011_document_shares.sql
-- ====================================================================
create table if not exists document_shares (
  document_id uuid primary key references documents(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade not null,
  share_id uuid not null unique default gen_random_uuid(),
  created_at timestamptz not null default now()
);

create index if not exists document_shares_share_id_idx on document_shares(share_id);
create index if not exists document_shares_user_id_idx on document_shares(user_id);

alter table document_shares enable row level security;

create policy "Users can read own document shares"
  on document_shares for select
  using (auth.uid() = user_id);

create policy "Users can create own document shares"
  on document_shares for insert
  with check (
    auth.uid() = user_id
    and exists (
      select 1
      from documents
      where documents.id = document_shares.document_id
        and documents.user_id = auth.uid()
    )
  );

create policy "Users can delete own document shares"
  on document_shares for delete
  using (auth.uid() = user_id);

-- END 011_document_shares.sql

-- ====================================================================
-- BEGIN 012_conversation_segments.sql
-- ====================================================================
-- conversation_segments: internal topic segments within a single conversation
create table if not exists conversation_segments (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references conversations(id) on delete cascade,
  user_id uuid not null references users(id) on delete cascade,
  status text not null default 'active' check (status in ('active', 'closed', 'archived')),
  title text,
  summary text,
  summary_embedding vector(1536),
  topic_key text,
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  last_active_at timestamptz not null default now(),
  message_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb
);

-- Enforce single active segment per conversation
create unique index if not exists idx_one_active_segment
  on conversation_segments (conversation_id)
  where status = 'active';

-- Add segment_id to messages (nullable during rollout)
alter table messages
  add column if not exists segment_id uuid references conversation_segments(id) on delete set null;

-- Also add source_segment_id to user_memories (Phase 1 added kind/pinned; we add the FK)
alter table user_memories
  add column if not exists source_segment_id uuid references conversation_segments(id) on delete set null;

-- Indexes
create index if not exists idx_segments_conversation on conversation_segments (conversation_id);
create index if not exists idx_segments_user on conversation_segments (user_id);
create index if not exists idx_segments_status on conversation_segments (conversation_id, status);
create index if not exists idx_messages_segment on messages (segment_id) where segment_id is not null;

-- END 012_conversation_segments.sql

-- ====================================================================
-- BEGIN 013_memory_classes.sql
-- ====================================================================
-- Add memory classification columns to user_memories.
-- The source_segment_id FK is added by 012_conversation_segments.sql.

alter table user_memories
  add column if not exists kind text not null default 'profile'
    check (kind in ('profile', 'project', 'preference', 'archive')),
  add column if not exists pinned boolean not null default false;

-- Existing memories default to 'profile' kind which is correct

-- END 013_memory_classes.sql

-- ====================================================================
-- BEGIN 014_segment_artifacts.sql
-- ====================================================================
-- segment_artifacts: durable outputs tied to internal conversation segments
-- Depends on 012_conversation_segments.sql.
do $$
begin
  if to_regclass('public.conversation_segments') is null then
    raise exception
      '014_segment_artifacts.sql requires 012_conversation_segments.sql to be applied first';
  end if;
end;
$$;

create table if not exists segment_artifacts (
  id uuid primary key default gen_random_uuid(),
  segment_id uuid not null references conversation_segments(id) on delete cascade,
  conversation_id uuid not null references conversations(id) on delete cascade,
  user_id uuid not null references users(id) on delete cascade,
  source_message_id uuid references messages(id) on delete set null,
  assistant_message_id uuid references messages(id) on delete set null,
  kind text not null default 'analysis' check (kind in ('memo', 'analysis', 'summary', 'other')),
  title text not null,
  summary text not null,
  content text not null default '',
  summary_embedding vector(1536),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_segment_artifacts_segment on segment_artifacts (segment_id, created_at desc);
create index if not exists idx_segment_artifacts_conversation on segment_artifacts (conversation_id, created_at desc);
create index if not exists idx_segment_artifacts_user on segment_artifacts (user_id, created_at desc);

create or replace function update_segment_artifacts_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger segment_artifacts_updated_at
  before update on segment_artifacts
  for each row execute procedure update_segment_artifacts_updated_at();

alter table segment_artifacts enable row level security;

create policy "Users can read own segment artifacts"
  on segment_artifacts for select
  using (auth.uid() = user_id);

create policy "Users can create own segment artifacts"
  on segment_artifacts for insert
  with check (auth.uid() = user_id);

create policy "Users can update own segment artifacts"
  on segment_artifacts for update
  using (auth.uid() = user_id);

create policy "Users can delete own segment artifacts"
  on segment_artifacts for delete
  using (auth.uid() = user_id);

-- END 014_segment_artifacts.sql

-- ====================================================================
-- BEGIN 015_conversation_segments_rls.sql
-- ====================================================================
alter table public.conversation_segments enable row level security;

drop policy if exists "Users can read own conversation segments" on public.conversation_segments;
create policy "Users can read own conversation segments"
  on public.conversation_segments
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can create own conversation segments" on public.conversation_segments;
create policy "Users can create own conversation segments"
  on public.conversation_segments
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own conversation segments" on public.conversation_segments;
create policy "Users can update own conversation segments"
  on public.conversation_segments
  for update
  using (auth.uid() = user_id);

drop policy if exists "Users can delete own conversation segments" on public.conversation_segments;
create policy "Users can delete own conversation segments"
  on public.conversation_segments
  for delete
  using (auth.uid() = user_id);

-- END 015_conversation_segments_rls.sql

-- ====================================================================
-- BEGIN 016_projects.sql
-- ====================================================================
-- projects: user-visible containers that bundle a docs folder, chat segments,
-- and artifacts under one named workspace.
-- Segments are tagged to a project via conversation_segments.metadata->>'project_id'
-- (no schema change required on that table). Documents are bound by matching folder.

create table if not exists projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id) on delete cascade,
  name text not null,
  folder text not null,
  description text,
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_projects_user on projects (user_id, created_at desc);
create unique index if not exists idx_projects_user_folder on projects (user_id, folder);

create or replace function update_projects_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger projects_updated_at
  before update on projects
  for each row execute procedure update_projects_updated_at();

alter table projects enable row level security;

create policy "Users can read own projects"
  on projects for select
  using (auth.uid() = user_id);

create policy "Users can create own projects"
  on projects for insert
  with check (auth.uid() = user_id);

create policy "Users can update own projects"
  on projects for update
  using (auth.uid() = user_id);

create policy "Users can delete own projects"
  on projects for delete
  using (auth.uid() = user_id);

-- Helps the project detail view query "segments in this project" efficiently.
create index if not exists idx_conversation_segments_project
  on conversation_segments ((metadata->>'project_id'));

-- END 016_projects.sql

-- ====================================================================
-- BEGIN 017_project_conversations.sql
-- ====================================================================
-- Per-project conversations ("Spaces").
--
-- Until now every user had a single conversation and all channels shared it,
-- so distinct topics (markets, health, …) piled into one messy thread. This
-- gives each project its own conversation; the pre-existing conversation keeps
-- project_id = NULL and becomes the default "General" space. Telegram/cron keep
-- landing on General because they pass no project.
--
-- Segments, documents, artifacts already scope to a project via
-- conversation_segments.metadata->>'project_id' and the docs folder; this simply
-- adds the missing scope on the messages/conversation thread itself.

alter table conversations
  add column if not exists project_id uuid references projects(id) on delete cascade;

-- Exactly one conversation per (user, project). NULL project_id collapses to a
-- fixed sentinel so the "General" space is also unique per user (a plain unique
-- index would treat every NULL as distinct and allow duplicates).
--
-- NOTE: if a user somehow already has more than one conversation row, this index
-- will fail to create. Inspect with:
--   select user_id, count(*) from conversations group by 1 having count(*) > 1;
-- and consolidate before applying.
create unique index if not exists idx_conversations_user_project
  on conversations (user_id, coalesce(project_id, '00000000-0000-0000-0000-000000000000'::uuid));

-- Helps resolve "this project's conversation" quickly.
create index if not exists idx_conversations_project
  on conversations (project_id)
  where project_id is not null;

-- END 017_project_conversations.sql

-- ====================================================================
-- BEGIN 018_space_instructions_and_scoped_memory.sql
-- ====================================================================
-- Slice 2: per-space identity + scoped memory.
--
-- Part 1 — per-space instructions: a free-text directive attached to a project
-- ("you are a markets analyst, be terse, always cite a source"). It layers into
-- the system prompt via buildProjectContextSection so each space behaves like a
-- distinct assistant while General stays generic.
--
-- Part 2 — scoped memory: until now every memory was global, so a Health fact
-- could surface mid-markets conversation. Each memory now carries an optional
-- project_id. A NULL project_id is a *global* fact (visible in every space); a
-- set project_id is a *space* fact (visible only in that space). Recall filters
-- to `project_id IS NULL OR project_id = <active>`.
--
-- Prereq: migration 017 (conversations.project_id) must be applied first.
--
-- VERIFY AFTER APPLYING (both `if exists` drops below fail SILENTLY if their
-- name/signature doesn't match, leaving the feature broken while reporting
-- success). Run these two and confirm the expected result:
--   -- must return ZERO rows (old unique(user_id, topic) is gone):
--   select conname from pg_constraint
--     where conrelid = 'public.user_memories'::regclass and contype = 'u';
--   -- must return exactly 1 (no leftover RPC overload → no PGRST203):
--   select count(*) from pg_proc where proname = 'match_user_memories';

-- Wrapped in a transaction so it's all-or-nothing: if any step errors (e.g. the
-- unique index), the drop constraint above it rolls back too, so the table is
-- never left without uniqueness protection. None of these use CONCURRENTLY, so
-- they're all transaction-safe.
begin;

-- Part 1 -----------------------------------------------------------------------
alter table projects
  add column if not exists instructions text;

-- Part 2 -----------------------------------------------------------------------
alter table user_memories
  add column if not exists project_id uuid references projects(id) on delete cascade;

-- The old unique(user_id, topic) would collide the same topic across spaces
-- (a Markets "diet" vs a Health "diet"), silently no-opping scoped writes.
-- Drop it and replace with a (user, space, topic) uniqueness that treats NULL
-- project_id as a fixed sentinel so global topics stay unique per user.
alter table user_memories
  drop constraint if exists user_memories_user_id_topic_key;

create unique index if not exists idx_user_memories_user_project_topic
  on user_memories (
    user_id,
    coalesce(project_id, '00000000-0000-0000-0000-000000000000'::uuid),
    topic
  );

create index if not exists idx_user_memories_project
  on user_memories (project_id)
  where project_id is not null;

-- Recall RPC: scope semantic matches to the active space plus globals.
-- NOTE: CREATE OR REPLACE with a new argument list creates a *second* overload
-- (PGRST203 ambiguity on call), so drop the old 4-arg signature explicitly first.
drop function if exists public.match_user_memories(vector, uuid, float, int);

create or replace function public.match_user_memories(
  query_embedding vector(1536),
  match_user_id uuid,
  match_project_id uuid default null,
  match_threshold float default 0.3,
  match_count int default 20
)
returns table (
  id uuid,
  topic text,
  content text,
  updated_at timestamptz,
  similarity float
)
language sql
stable
as $$
  select
    um.id,
    um.topic,
    um.content,
    um.updated_at,
    1 - (um.embedding <=> query_embedding) as similarity
  from public.user_memories um
  where um.user_id = match_user_id
    and (um.project_id is null or um.project_id = match_project_id)
    and um.embedding is not null
    and 1 - (um.embedding <=> query_embedding) > match_threshold
  order by um.embedding <=> query_embedding
  limit match_count;
$$;

commit;

-- END 018_space_instructions_and_scoped_memory.sql

-- ====================================================================
-- BEGIN 019_space_persona.sql
-- ====================================================================
-- Slice 3: per-space persona (visual identity).
--
-- Each space can carry an emoji and an accent color so it reads as a distinct
-- assistant at a glance — in the space switcher, the chat header, and the
-- spaces list. Both are optional; when unset the UI falls back to the existing
-- hashed-hue dot, so pre-existing spaces keep working with no backfill.
--
--   emoji — a single emoji character, e.g. '📈' (NULL = no emoji, show a dot).
--   color — an accent as a hex string, e.g. '#14b8a6' (NULL = hashed fallback).
--
-- Purely additive: two nullable columns, no drops, no data movement. Safe to
-- re-run (add column if not exists).

begin;

alter table projects add column if not exists emoji text;
alter table projects add column if not exists color text;

commit;

-- VERIFY AFTER APPLYING — both columns should now exist:
--   select column_name from information_schema.columns
--   where table_name = 'projects' and column_name in ('emoji', 'color');
--   -- expect two rows: color, emoji

-- END 019_space_persona.sql

-- ====================================================================
-- BEGIN 020_space_suggestions.sql
-- ====================================================================
-- Slice 4: per-space starter suggestions.
--
-- Each space can carry a short list of starter prompts, prefilled from its
-- template at creation. The chat home renders them as the empty-state cards
-- when you're inside that space, so a space reads as a specialized assistant
-- (its own suggestions) rather than General with a colored dot.
--
--   suggestions — text[] of short prompts, e.g. ARRAY['Summarize today''s macro news'].
--                 NULL or empty = fall back to the general starter cards.
--
-- Purely additive: one nullable array column, no drops, no data movement. Safe
-- to re-run (add column if not exists). Existing spaces keep working (NULL →
-- general starters); only spaces created from a template after this migration
-- carry suggestions.

begin;

alter table projects add column if not exists suggestions text[];

commit;

-- VERIFY AFTER APPLYING — the column should now exist:
--   select column_name, data_type from information_schema.columns
--   where table_name = 'projects' and column_name = 'suggestions';
--   -- expect one row: suggestions | ARRAY

-- END 020_space_suggestions.sql

-- ====================================================================
-- BEGIN 021_space_tool_allowlist.sql
-- ====================================================================
-- Slice 6: per-space tool allowlist.
--
-- Each space can restrict which optional tools its assistant may use, so an
-- "Investing" space can be prevented from touching Gmail, or a "Reading" space
-- from scheduling tasks. This is the capability half of a space's identity:
-- alongside its instructions and memory scope, it now also decides what the
-- assistant is allowed to *do*.
--
--   tool_allowlist — text[] of gateable tool names the space may use.
--                    NULL  = unrestricted (all tools) — the default, and what
--                            every existing space keeps.
--                    []    = no gateable tools (chat + core essentials only).
--                    [...] = exactly those gateable tools, plus the always-on
--                            core tools (memory, planning, cards) which are
--                            never gated.
--
-- Purely additive: one nullable array column, no drops, no data movement. Safe
-- to re-run (add column if not exists). Existing spaces keep working (NULL →
-- all tools). Enforcement lives in tool-registry.getAvailable; a missing column
-- degrades to unrestricted, so chat never breaks if this hasn't been applied.

begin;

alter table projects add column if not exists tool_allowlist text[];

commit;

-- VERIFY AFTER APPLYING — the column should now exist:
--   select column_name, data_type from information_schema.columns
--   where table_name = 'projects' and column_name = 'tool_allowlist';
--   -- expect one row: tool_allowlist | ARRAY

-- END 021_space_tool_allowlist.sql

-- ====================================================================
-- BEGIN 022_scheduled_task_spaces.sql
-- ====================================================================
-- Proactivity: Space-scoped scheduled tasks.
--
-- A scheduled task can belong to a Space, so a recurring briefing or reminder
-- created inside a Space runs as *that* assistant — its instructions, scoped
-- memory, tool allowlist, and its own conversation thread — rather than as
-- General. This is what turns Spaces from a passive filing system into
-- proactive, specialized assistants ("every Monday, summarize the market open"
-- scheduled in the Investing Space runs with the Investing persona).
--
--   project_id — nullable FK to projects. NULL = General (the default, and what
--                every existing task keeps). ON DELETE SET NULL so deleting a
--                Space demotes its tasks to General rather than dropping them.
--
-- Purely additive: one nullable column. Safe to re-run. The cron worker reads
-- the column off the row and degrades to NULL (General) when it's absent, so
-- scheduling and execution keep working before this migration is applied.

begin;

alter table public.scheduled_tasks
  add column if not exists project_id uuid references public.projects(id) on delete set null;

create index if not exists idx_scheduled_tasks_project
  on public.scheduled_tasks(project_id);

commit;

-- VERIFY AFTER APPLYING:
--   select column_name, data_type from information_schema.columns
--   where table_name = 'scheduled_tasks' and column_name = 'project_id';
--   -- expect one row: project_id | uuid

-- END 022_scheduled_task_spaces.sql

-- ====================================================================
-- BEGIN 023_workflow_execution_claims.sql
-- ====================================================================
-- Atomically claim a workflow across manual and cron workers.
ALTER TABLE public.scheduled_tasks
  ADD COLUMN IF NOT EXISTS execution_token uuid,
  ADD COLUMN IF NOT EXISTS execution_started_at timestamptz;

CREATE OR REPLACE FUNCTION public.claim_workflow_execution(
  task_id uuid, owner_id uuid, claim_token uuid, expected_last_run timestamptz
) RETURNS boolean
LANGUAGE sql SECURITY DEFINER SET search_path = public
AS $$
  WITH claimed AS (
    UPDATE scheduled_tasks
       SET execution_token = claim_token, execution_started_at = now()
     WHERE id = task_id AND user_id = owner_id
       AND last_run_at IS NOT DISTINCT FROM expected_last_run
       AND (execution_token IS NULL OR execution_started_at < now() - interval '10 minutes')
    RETURNING id
  ) SELECT EXISTS(SELECT 1 FROM claimed);
$$;
REVOKE ALL ON FUNCTION public.claim_workflow_execution(uuid, uuid, uuid, timestamptz) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_workflow_execution(uuid, uuid, uuid, timestamptz) TO service_role;

-- END 023_workflow_execution_claims.sql
