#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
migrations_dir="$repo_root/supabase/migrations"
output_file="$repo_root/supabase/schema.sql"
tmp_file="$(mktemp)"

cleanup() {
  rm -f "$tmp_file"
}
trap cleanup EXIT

{
  echo "-- Fresh-install bootstrap schema for Hada."
  echo "-- Generated from supabase/migrations for brand-new databases."
  echo "-- Do not edit this file directly."
  echo "-- Regenerate with: npm run db:schema"
  echo "-- Existing databases should continue applying incremental migrations."
  echo

  while IFS= read -r migration; do
    echo "-- ===================================================================="
    echo "-- BEGIN $(basename "$migration")"
    echo "-- ===================================================================="
    cat "$migration"
    echo
    echo "-- END $(basename "$migration")"
    echo
  done < <(find "$migrations_dir" -maxdepth 1 -type f -name "*.sql" | LC_ALL=C sort)
} > "$tmp_file"

mv "$tmp_file" "$output_file"
echo "Wrote $output_file"
